# Generated by Django 3.0.3 on 2020-03-08 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0002_event'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='slug',
        ),
        migrations.AlterField(
            model_name='event',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
